project:
    root:       "./../"
    storage:    "./results"
    rules:      "./rules"
analysis:
    ignore:
        - ".*\\.swp"
        - ".git"
        - "composer"
        - ".*/lib"
        - ".*/test"
        - "dicto"
        - "libs"
        - "Modules/Chatroom/chat"
        - "Services/ActiveRecord/Fields/Converter/templates"
        - "Services/Mail/phpmailer"
        - "Services/PDFGeneration/classes/tcpdf"
        - "Services/Object/test/testmodule[.]xml"
        - "setup/sql"
        - ".*/HFile_.*"
        - ".*lang"
        - ".*[.]dtd"
        - ".*[.]exe"
        - ".*[.]eot"
        - ".*[.]gif"
        - ".*[.]graffle"
        - ".*[.]jar"
        - ".*[.]java"
        - ".*[.]jpeg"
        - ".*[.]jpg"
        - ".*[.]js"
        - ".*[.]mp3"
        - ".*[.]mp4"
        - ".*[.]ogg"
        - ".*[.]png"
        - ".*[.]psd"
        - ".*[.]rdf"
        - ".*[.]svg"
        - ".*[.]swf"
        - ".*[.]ttf"
        - ".*[.]woff"
        - ".*[.]woff2"
        - ".*[.]xml"
        - ".*[.]xpi"
        - ".*[.]xsd"
        - ".*[.]xsl"
        - ".*/test/.*"
